# Generated by Django 6.0 on 2025-12-14 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='简短的个人介绍', max_length=500, verbose_name='个人简介')),
                ('avatar', models.ImageField(default='avatars/default.jpg', help_text='用户头像图片', upload_to='avatars/', verbose_name='头像')),
                ('location', models.CharField(blank=True, help_text='用户所在城市或地区', max_length=100, verbose_name='所在地')),
                ('website', models.URLField(blank=True, help_text='用户的个人网站或博客链接', verbose_name='个人网站')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(help_text='关联的用户账号', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'ordering': ['-created_at'],
            },
        ),
    ]
