# Generated by Django 6.0 on 2025-12-14 09:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='分类的名称，必须唯一', max_length=100, unique=True, verbose_name='分类名称')),
                ('slug', models.SlugField(help_text='用于 URL 的简短标签，只能包含字母、数字、下划线或连字符', max_length=100, unique=True, verbose_name='URL别名')),
                ('description', models.TextField(blank=True, help_text='分类的详细描述（可选）', verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('slug', models.SlugField(unique=True, verbose_name='URL别名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='文章的标题，最多 200 个字符', max_length=200, verbose_name='文章标题')),
                ('slug', models.SlugField(help_text='用于生成文章的 URL', max_length=200, unique_for_date='publish', verbose_name='URL别名')),
                ('excerpt', models.TextField(blank=True, help_text='文章的简短摘要（可选）', max_length=500, verbose_name='摘要')),
                ('content', models.TextField(help_text='文章的正文内容', verbose_name='正文内容')),
                ('featured_image', models.ImageField(blank=True, help_text='文章的特色图片（可选）', null=True, upload_to='blog/images/%Y/%m/%d/', verbose_name='特色图片')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', help_text='文章的发布状态', max_length=10, verbose_name='状态')),
                ('views', models.PositiveIntegerField(default=0, help_text='文章的浏览次数', verbose_name='浏览次数')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, help_text='文章的发布时间', verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(help_text='文章的作者（外键关联到 User 模型）', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(blank=True, help_text='文章所属的分类（可选）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='分类')),
                ('tags', models.ManyToManyField(blank=True, help_text='文章的标签（多对多关系）', related_name='posts', to='blog.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='评论的文本内容', verbose_name='评论内容')),
                ('is_approved', models.BooleanField(default=True, help_text='管理员可以审核评论', verbose_name='是否通过审核')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(help_text='发表评论的用户', on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('parent', models.ForeignKey(blank=True, help_text='如果是回复，则指向被回复的评论', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment', verbose_name='父评论')),
                ('post', models.ForeignKey(help_text='评论所属的文章', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='所属文章')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['post', 'created_at'], name='blog_commen_post_id_5fee65_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-publish'], name='blog_post_publish_bb7600_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status'], name='blog_post_status_02ce19_idx'),
        ),
    ]
